import { AuthProvider } from "@/src/features/auth/providers/auth-provider/auth-provider.component";
import { QueryClientProviderComponent } from "@/src/features/query/providers/query-client-provider.component";
import { getCurrentUserForPage } from "@/src/utils/server/get-current-user-for-page.util";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialUser = await getCurrentUserForPage();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <QueryClientProviderComponent>
          <AuthProvider initialUser={initialUser}>{children}</AuthProvider>
        </QueryClientProviderComponent>
      </body>
    </html>
  );
}
